//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class resident
    {
        public int sn { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EnglishName { get; set; }
        public string gender { get; set; }
        public string socialID { get; set; }
        public string birthday { get; set; }
        public string telephone1 { get; set; }
        public string telephone2 { get; set; }
        public string telephone3 { get; set; }
        public string address { get; set; }
    }
}
